# Generated by Django 5.1.7 on 2025-03-26 19:59

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverageentry',
            name='additives',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sugar', 'sugar'), ('milk', 'milk'), ('cream', 'cream'), ('lime', 'lime'), ('honey', 'honey'), ('artifical-sweetners', 'artifical-sweetners'), ('protein-powders', 'protein-powders'), ('electrolyte-powders', 'electrolyte-powders')], max_length=83, null=True),
        ),
    ]
