# Generated by Django 5.1.7 on 2025-03-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_tracker', '0002_alter_beverageentry_additives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverageentry',
            name='additives',
            field=models.JSONField(blank=True, help_text="Enter as a JSON list of additives (e.g., ['sugar', 'milk', 'custom additive'])", null=True),
        ),
    ]
