# Generated by Django 5.1.7 on 2025-03-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_tracker', '0003_alter_beverageentry_additives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverageentry',
            name='additives',
            field=models.JSONField(blank=True, help_text='Select from the list or enter custom additives (comma-separated)', null=True),
        ),
    ]
