# Generated by Django 5.1.7 on 2025-03-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_tracker', '0004_alter_beverageentry_additives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beverageentry',
            name='additives',
        ),
        migrations.CreateModel(
            name='Additives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sugar', 'Sugar'), ('milk', 'Milk'), ('cream', 'Cream'), ('lime', 'Lime'), ('honey', 'Honey'), ('artificial_sweeteners', 'Artificial Sweeteners'), ('protein_powders', 'Protein Powders'), ('electrolyte_powders', 'Electrolyte Powders')], max_length=50)),
                ('beverage_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additives', to='intake_tracker.beverageentry')),
            ],
        ),
    ]
