# Generated by Django 5.1.7 on 2025-03-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_tracker', '0006_additives_custom_additives_alter_additives_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additives',
            name='custom_additives',
            field=models.CharField(blank=True, help_text='Specify if the additive is not listed above.', max_length=50, null=True),
        ),
    ]
