# Generated by Django 5.1.7 on 2025-03-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake_tracker', '0007_alter_additives_custom_additives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverageentry',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
